# Generated by Django 2.0.4 on 2018-06-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='id',
        ),
        migrations.AddField(
            model_name='database',
            name='pname',
            field=models.CharField(default=2, max_length=22, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
