# Generated by Django 2.0.4 on 2018-06-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20180628_0815'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='password',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='database',
            name='pname',
            field=models.CharField(blank=True, max_length=22, primary_key=True, serialize=False),
        ),
    ]
