# Generated by Django 2.0.4 on 2018-06-28 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20180628_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='database',
            name='password',
        ),
    ]
