# Generated by Django 2.0.4 on 2018-04-26 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=30)),
                ('email_verified', models.BooleanField(default=False)),
                ('family_name', models.CharField(default=None, max_length=255)),
                ('given_name', models.CharField(default=None, max_length=255)),
                ('middle_name', models.CharField(default=None, max_length=255)),
                ('picture', models.CharField(default=None, max_length=40, null=True)),
                ('birthdate', models.DateField()),
                ('locale', models.CharField(choices=[('ru-RU', 'Российская'), ('en-US', 'English')], max_length=5)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_username', models.CharField(blank=True, max_length=255, null=True)),
                ('profile', models.CharField(blank=True, max_length=255, null=True)),
                ('website', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('zoneinfo', models.CharField(blank=True, max_length=255, null=True)),
                ('sub', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
