# Generated by Django 2.0.4 on 2018-06-27 03:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20180617_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='db_count',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
