# Generated by Django 2.0.4 on 2018-06-27 03:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_user_db_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='db_count',
            field=models.IntegerField(default=0, max_length=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
