# Generated by Django 2.0.4 on 2018-06-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20180627_0930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='db_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='db_pass',
        ),
        migrations.AddField(
            model_name='user',
            name='db_password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
